language: python
python:
  - '3.5'
  - '3.6'

matrix:
  include:
    - python: '3.7'
      dist: xenial
      sudo: true

install:
  - python setup.py install

script:
  - pytest --cov=scclient tests/

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
