language: python
python:
  - '3.5'
  - '3.6'

install:
  - python setup.py test
  - python setup.py install

script:
  - pytest --cov=scclient tests/

after_success:
  - coverage xml
  - python-codacy-coverage -r coverage.xml
